### ISSUE TITLE
Failed jobs: Exception 'NameError' / uninitialized constant MyThingyJob

### ISSUE THREAD

**Issue by john-999** [resque/resque-scheduler#383]
I just started to get 'NameError' exceptions:

```
uninitialized constant MyThingyJob
```

My application.rb has the line:

```
config.autoload_paths += Dir[Rails.root.join('lib', '{**}')]
```

...which should load the job file located in a subfolder (in the models folder).

Using:
- resque (1.25.2)
- resque-scheduler (2.5.5)
- resque-pool (0.3.0)

**Comment by lanrion** [comment]
Sample the problem to me。
```
A NameError occurred in background at 2015-11-04 20:59:00 :

  uninitialized constant OrderJob
  /www/test_pro/shared/bundle/ruby/2.1.0/gems/resque-1.25.2/lib/resque/job.rb:114:in `block in constantize'

  -------------------------------
Backtrace:
-------------------------------

  /shared/bundle/ruby/2.1.0/gems/resque-1.25.2/lib/resque/job.rb:114:in `block in constantize'
  /shared/bundle/ruby/2.1.0/gems/resque-1.25.2/lib/resque/job.rb:108:in `each'
  /shared/bundle/ruby/2.1.0/gems/resque-1.25.2/lib/resque/job.rb:108:in `constantize'
  /shared/bundle/ruby/2.1.0/gems/resque-1.25.2/lib/resque/job.rb:268:in `payload_class'
  /shared/bundle/ruby/2.1.0/gems/resque-1.25.2/lib/resque/job.rb:210:in `perform'
  /shared/bundle/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'
  /shared/bundle/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:189:in `block in work'
  /shared/bundle/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop'
  /shared/bundle/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `work'
  /shared/bundle/ruby/2.1.0/gems/resque-1.25.2/lib/resque/tasks.rb:41:in `block (2 levels) in <top (required)>'
  /shared/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
```

**Comment by lanrion** [comment]
resque_static_schedule.yml:
```yml
---
OrderJob:
  description: "desc"
  queue: order_jobs
  class: "OrderJob"
```
