### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by wesgurn** [resque/resque-scheduler#480]
Any chance we can get a bump on the version that folds in all the changes since the 4.0.0 release?

**Comment by jeffutter** [comment]
+1 to this. I'm getting: 
```
NoMethodError: undefined method `env' for Rails:Module
/usr/local/rvm/gems/ruby-2.2.2/gems/resque-scheduler-4.0.0/lib/resque/scheduler/configuration.rb:16:in `env'
/usr/local/rvm/gems/ruby-2.2.2/gems/resque-scheduler-4.0.0/lib/resque/scheduler.rb:399:in `env_str'
/usr/local/rvm/gems/ruby-2.2.2/gems/resque-scheduler-4.0.0/lib/resque/scheduler.rb:403:in `build_procline'
/usr/local/rvm/gems/ruby-2.2.2/gems/resque-scheduler-4.0.0/lib/resque/scheduler.rb:376:in `procline'
/usr/local/rvm/gems/ruby-2.2.2/gems/resque-scheduler-4.0.0/lib/resque/scheduler.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.2.2/gems/resque-scheduler-4.0.0/lib/resque/scheduler/cli.rb:117:in `run_forever'
/usr/local/rvm/gems/ruby-2.2.2/gems/resque-scheduler-4.0.0/lib/resque/scheduler/tasks.rb:18:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
``` on my non-rails app

this seems to have been fixed since the release

**Comment by dominicsayers** [comment]
:+1:

**Comment by meatballhat** [comment]
Please yell if the latest version is still causing issues for you!
