### ISSUE TITLE
Stand alone fails with "uninitialized constant Resque::Scheduler::Redis"

### ISSUE THREAD

**Issue by Qwertie-** [resque/resque-scheduler#683]
I installed the gem on its own and then run `resque-scheduler --help` and it fails with the error
```
/home/lukepicciau/.rvm/gems/ruby-2.3.3/gems/resque-scheduler-4.4.0/lib/resque/scheduler.rb:17:in `<module:Scheduler>': uninitialized constant Resque::Scheduler::Redis (NameError)
	from /home/lukepicciau/.rvm/gems/ruby-2.3.3/gems/resque-scheduler-4.4.0/lib/resque/scheduler.rb:11:in `<module:Resque>'
	from /home/lukepicciau/.rvm/gems/ruby-2.3.3/gems/resque-scheduler-4.4.0/lib/resque/scheduler.rb:10:in `<top (required)>'
	from /home/lukepicciau/.rvm/gems/ruby-2.3.3/gems/resque-scheduler-4.4.0/lib/resque-scheduler.rb:2:in `require_relative'
	from /home/lukepicciau/.rvm/gems/ruby-2.3.3/gems/resque-scheduler-4.4.0/lib/resque-scheduler.rb:2:in `<top (required)>'
	from /home/lukepicciau/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/lukepicciau/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/lukepicciau/.rvm/gems/ruby-2.3.3/gems/resque-scheduler-4.4.0/exe/resque-scheduler:4:in `<top (required)>'
	from /home/lukepicciau/.rvm/gems/ruby-2.3.3/bin/resque-scheduler:23:in `load'
	from /home/lukepicciau/.rvm/gems/ruby-2.3.3/bin/resque-scheduler:23:in `<main>'
	from /home/lukepicciau/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:24:in `eval'
	from /home/lukepicciau/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:24:in `<main>'
```

Same result on Fedora 29, ruby alpine container and ruby debian container.

**Comment by jeremy** [comment]
Duplicates #665. Fixed by #671.
