### ISSUE TITLE
wrong number of arguments (given 4, expected 3) when calling zrangebyscore

### ISSUE THREAD

**Issue by arbesulo** [resque/resque-scheduler#708]
Hi, I'm getting the following error after upgrading to ruby 3.0.1

Any ideas?

```
bundle exec rake environment resque:scheduler
resque-scheduler: [INFO] 2021-04-15T07:13:03+00:00: Starting
/usr/local/bundle/gems/resque-scheduler-4.4.0/lib/resque/scheduler/lock/base.rb:50: warning: Socket.gethostbyname is deprecated; use Addrinfo.getaddrinfo instead.
resque-scheduler: [INFO] 2021-04-15T07:13:03+00:00: Master scheduler
resque-scheduler: [INFO] 2021-04-15T07:13:03+00:00: Reloading Schedule
resque-scheduler: [INFO] 2021-04-15T07:13:03+00:00: Loading Schedule
resque-scheduler: [INFO] 2021-04-15T07:13:03+00:00: Schedule empty! Set Resque.schedule
resque-scheduler: [INFO] 2021-04-15T07:13:03+00:00: Schedules Loaded
rake aborted!
ArgumentError: wrong number of arguments (given 4, expected 3)
/usr/local/bundle/gems/redis-4.2.5/lib/redis.rb:1961:in `zrangebyscore'
/usr/local/bundle/gems/redis-objects-1.5.0/lib/redis/objects/connection_pool_proxy.rb:10:in `block in method_missing'
/usr/local/bundle/gems/connection_pool-2.2.5/lib/connection_pool.rb:63:in `block (2 levels) in with'
/usr/local/bundle/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `handle_interrupt'
/usr/local/bundle/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `block in with'
/usr/local/bundle/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `handle_interrupt'
/usr/local/bundle/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `with'
/usr/local/bundle/gems/redis-objects-1.5.0/lib/redis/objects/connection_pool_proxy.rb:10:in `method_missing'
/usr/local/bundle/gems/redis-namespace-1.8.1/lib/redis/namespace.rb:476:in `call_with_namespace'
/usr/local/bundle/gems/redis-namespace-1.8.1/lib/redis/namespace.rb:352:in `block (2 levels) in <class:Namespace>'
/usr/local/bundle/gems/resque-2.0.0/lib/resque/data_store.rb:65:in `method_missing'
/usr/local/bundle/gems/resque-scheduler-4.4.0/lib/resque/scheduler/delaying_extensions.rb:310:in `search_first_delayed_timestamp_in_range'
/usr/local/bundle/gems/resque-scheduler-4.4.0/lib/resque/scheduler/delaying_extensions.rb:114:in `next_delayed_timestamp'
/usr/local/bundle/gems/resque-scheduler-4.4.0/lib/resque/scheduler.rb:185:in `handle_delayed_items'
/usr/local/bundle/gems/resque-scheduler-4.4.0/lib/resque/scheduler.rb:68:in `block in run'
/usr/local/bundle/gems/resque-scheduler-4.4.0/lib/resque/scheduler.rb:56:in `loop'
/usr/local/bundle/gems/resque-scheduler-4.4.0/lib/resque/scheduler.rb:56:in `run'
/usr/local/bundle/gems/resque-scheduler-4.4.0/lib/resque/scheduler/cli.rb:117:in `run_forever'
/usr/local/bundle/gems/resque-scheduler-4.4.0/lib/resque/scheduler/tasks.rb:18:in `block (2 levels) in <main>'
/usr/local/bundle/bin/bundle:23:in `load'
/usr/local/bundle/bin/bundle:23:in `<main>'
Tasks: TOP => resque:scheduler
(See full trace by running task with --trace)
```

**Comment by byroot** [comment]
Looks like a bug in that ConnectionPoolProxy object: https://github.com/nateware/redis-objects/blob/210041769d84ff5efc253d4075468de5e5653e27/lib/redis/objects/connection_pool_proxy.rb

It clearly wasn't updated for Ruby 3.0. Please open an issue there.

**Comment by byroot** [comment]
Actually, there's a PR for it: https://github.com/nateware/redis-objects/pull/258

**Comment by WozniakMac** [comment]
I had almost this same error but without rails-object

Resque sheduler is not supporting ruby 3. And it's not supported since 2019 

```
resque_scheduler_1  | resque-scheduler: [INFO] 2021-06-28T06:31:04+00:00: Schedules Loaded
resque_scheduler_1  | rake aborted!
resque_scheduler_1  | ArgumentError: wrong number of arguments (given 4, expected 3)
resque_scheduler_1  | /usr/local/bundle/gems/redis-4.3.1/lib/redis.rb:1969:in `zrangebyscore'
resque_scheduler_1  | /usr/local/bundle/gems/redis-namespace-1.6.0/lib/redis/namespace.rb:442:in `call_with_namespace'
resque_scheduler_1  | /usr/local/bundle/gems/redis-namespace-1.6.0/lib/redis/namespace.rb:328:in `method_missing'
resque_scheduler_1  | /usr/local/bundle/gems/resque-2.0.0/lib/resque/data_store.rb:65:in `method_missing'
resque_scheduler_1  | /usr/local/bundle/gems/resque-scheduler-4.4.0/lib/resque/scheduler/delaying_extensions.rb:310:in `search_first_delayed_timestamp_in_range'
resque_scheduler_1  | /usr/local/bundle/gems/resque-scheduler-4.4.0/lib/resque/scheduler/delaying_extensions.rb:114:in `next_delayed_timestamp'
resque_scheduler_1  | /usr/local/bundle/gems/resque-scheduler-4.4.0/lib/resque/scheduler.rb:185:in `handle_delayed_items'
resque_scheduler_1  | /usr/local/bundle/gems/resque-scheduler-4.4.0/lib/resque/scheduler.rb:68:in `block in run'
resque_scheduler_1  | /usr/local/bundle/gems/resque-scheduler-4.4.0/lib/resque/scheduler.rb:56:in `loop'
resque_scheduler_1  | /usr/local/bundle/gems/resque-scheduler-4.4.0/lib/resque/scheduler.rb:56:in `run'
resque_scheduler_1  | /usr/local/bundle/gems/resque-scheduler-4.4.0/lib/resque/scheduler/cli.rb:117:in `run_forever'
resque_scheduler_1  | /usr/local/bundle/gems/resque-scheduler-4.4.0/lib/resque/scheduler/tasks.rb:18:in `block (2 levels) in <top (required)>'
resque_scheduler_1  | /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/cli/exec.rb:63:in `load'
resque_scheduler_1  | /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/cli/exec.rb:63:in `kernel_load'
resque_scheduler_1  | /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/cli/exec.rb:28:in `run'
resque_scheduler_1  | /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/cli.rb:474:in `exec'
resque_scheduler_1  | /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
resque_scheduler_1  | /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
resque_scheduler_1  | /usr/local/bundle/gem
s/bundler-2.2.21/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
resque_scheduler_1  | /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/cli.rb:30:in `dispatch'
resque_scheduler_1  | /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
resque_scheduler_1  | /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/cli.rb:24:in `start'
resque_scheduler_1  | /usr/local/bundle/gems/bundler-2.2.21/exe/bundle:49:in `block in <top (required)>'
resque_scheduler_1  | /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
resque_scheduler_1  | /usr/local/bundle/gems/bundler-2.2.21/exe/bundle:37:in `<top (required)>'
resque_scheduler_1  | /usr/local/bundle/bin/bundle:23:in `load'
resque_scheduler_1  | /usr/local/bundle/bin/bundle:23:in `<main>'
```

helped updating resque to current master

```
gem "resque", git: "https://github.com/resque/resque.git", ref: "be71bd1a3e10138284a259e496d7ae01da820646"
```
