### ISSUE TITLE
sadd deprecation warning

### ISSUE THREAD

**Issue by Jakanapes** [resque/resque-scheduler#772]
use with redis 4.8.1 results in

Redis#sadd will always return an Integer in Redis 5.0.0. Use Redis#sadd? instead.(called from: /Users/jakanapes/.gem/ruby/3.1.3/gems/redis-namespace-1.11.0/lib/redis/namespace.rb:564:in `wrapped_send')

I can see it being called here

/Users/jakanapes/.gem/ruby/3.1.3/gems/resque-scheduler-4.9.0/lib/resque/scheduler/delaying_extensions.rb:93:in `delayed_push'

**Comment by michelleheh** [comment]
We got a similar warnings, and our logs are flooded with the following.

```
Redis#sadd will always return an Integer in Redis 5.0.0. Use Redis#sadd? instead.
```

We tracked it down to https://github.com/resque/resque-scheduler/blob/master/lib/resque/scheduler/scheduling_extensions.rb where there are 3 usages of `redis.sadd`.
